### PR TITLE
chore: removed scripts/prefabs related to unused MOTD

### LINKED ISSUE #1906: Remove unused "message of the day" system
One of the launch features "message of the day" feature relies on the service `dclcms.club` and its not longer used. Also, this service will be deprecated soon. 

**Acceptance Criteria**
- Remove everything related to "message of the day" system

### PR DESCRIPTION
**Pull request by davidejensen**
## What does this PR change?

Fix #1906
Removes unused stuff related to MOTD

...

## How to test the changes?

1. Go to: https://play.decentraland.zone/?renderer-branch=chore/remove-message-of-the-day
2. Verify that everything works fine

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

**Comment by pravusjif** [comment]
There's a test that should be removed/fixed

**Comment by davidejensen** [comment]
> There's a test that should be removed/fixed

My bad, didn't see it was failing, I fixed the test!

**Review by AjimenezDCL — APPROVED** [review]
`ScriptableObjects/MOTDActive` should be removed as well. Approving anyway!

**Comment by davidejensen** [comment]
> `ScriptableObjects/MOTDActive` should be removed as well. Approving anyway!

Wait, I did remove it already

**Pull request merged**
