### PR TITLE
fix: out of scene bounds entities check

### PR DESCRIPTION
**Pull request by pravusjif**
## WHY
We have several issues that degrade the experience due to the scene bounds checker not evaluating entities at the pertinent moment:

- https://github.com/decentraland/unity-renderer/issues/2132
- https://github.com/decentraland/unity-renderer/issues/844
- https://github.com/decentraland/unity-renderer/issues/480
- https://github.com/decentraland/unity-renderer/issues/978

## WHAT
- Implements a new preliminary scene bounds check for entities using scenes "outer bounds", that is cheaper
    - Calls that preliminary check on transforms update and on shapdes update.
- Added missing scene bounds checks for Parametrized Shapes
- Added missing scene bounds check for entities after they are reparented
- Adds scene bounds check for entities with shape but without transform
- Increases a bit the CPU time budget for messages processing and for the Scene Bounds Checker processing (they use the same budget)
- Renamed some Scene Bounds Checker methods that were ambiguous and confusing
- Adds test scene bounds checking test coverage 

### https://github.com/decentraland/unity-renderer/issues/2132 issue
1. Spawn [at -12, -10](https://play.decentraland.zone/?renderer-branch=fix/OutOfSceneBoundsEntitiesCheck&LOCAL_COMMS&position=-12%2C-10) and wait until Genesis Plaza finishes loading (make sure the Scene Load Radius value in the settings is 4) 
2. Open Settings, change the Scene Load Radius to 1 and wait 5~ seconds
3. Change Scene Load Radius to 4 and close the settings panel, wait for 5~10 seconds after the Genesis Plaza finishes loading and notice that he "black and white" bug doesn't happen anymore
4. Steps 2 and 3 can be reproduced many times and the black and white bug won't happen again 
[Doing those steps from master's build will trigger the black and white bug]

### https://github.com/decentraland/unity-renderer/issues/844 issue
1. Spawn [at -12, -10](https://play.decentraland.zone/?renderer-branch=fix/OutOfSceneBoundsEntitiesCheck&LOCAL_COMMS&position=-12%2C-10)
2. Walk towards the tramline at -12, 0
3. Walk through the tramline to the west, and notice that no mesh is instantiated int the middle of the street

### https://github.com/decentraland/unity-renderer/issues/480 and https://github.com/decentraland/unity-renderer/issues/978 issues
1. Spawn [at -40, 2](https://play.decentraland.zone/?renderer-branch=fix/OutOfSceneBoundsEntitiesCheck&LOCAL_COMMS&position=-40%2C2)
2. Walk to -50, 1 and notice that the paint bucket that attaches to the player in that scene doesn't appear before you enter the scene

### CODE REVIEW

**Comment by pravusjif** [comment]
### Update
- Most cases of meshes outside their scene bounds are due to entities having their shape component added BEFORE their Transform component: resulting in the entity instantiated in the lower-left position of the scene base parcel (the scene local origin 0,0,0) until that entity has its Transform component and gets repositioned, rotated and scaled. 
- In Genesis Plaza many entities are having that problem, that's why they appear first in the scene's 0,0,0. Even the street parcels have that problem...
- When a scene with those kind of entities is being loaded far away from the player, due to the message processing throttling the affected entities take more time to receive their Transform component after they have their shape and are instantiated in the scene's local origin position. 

We should have the Scene Bounds Checker hide those entities when they are in the scene local origin position as they have most of their mesh outside the scene boundaries. The problem that arises with that is that after flagging those entities as "outside scene bounds" and disabling their renderers and colliders, it may take a while until they are re-evaluated and set as "inside scene bounds" again (re-enabling their renderers and colliders): there's time until those entities receive their first Transform component message (the messaging processing throttling for far away scenes prolongs that waiting time) and after that there's time until the Scene Bounds Checker actually re-evaluates those entities and detects them as being inside the scene bounds (the cpu budget throttling for the Scene Bounds Checker prolongs that waiting time when there are lots of entities to be evaluated)

### Current problem being debugged
For some reason the first time that Genesis Plaza loads (starting outside the plaza, as every test run for this implementation) the meshes are quickly processed and detected as inside boundaries, but if we reload the scene in the same session (so it starts using the cached assets in the asset library) it detects the entities as outside boundaries (because of the shapes without transform issue) and it takes A LOT of time to evaluate those entities again, due to CPU budget throttling, etc.

### Other problem found
I believe [SceneBoundsFeedbackStyle_Simple](https://github.com/decentraland/unity-renderer/blob/master/unity-renderer/Assets/Scripts/MainScripts/DCL/WorldRuntime/SceneBoundariesController/SceneBoundsFeedbackStyle_Simple.cs) shouldn't just toggle the renderers enabled value, it should take into account that shape's model `visible` value and use that instead of always enabling the renderers. To fix that a mini refactor is needed in that class.

**Comment by pravusjif** [comment]
Testing the same path with this PRs build and PROD's build, the Performance Meter Tool show a (significant?) drop in performance...
Screen Shot 2022-06-07 at 01 49 27

Screen Shot 2022-06-07 at 01 43 15

**Review by Kinerius — APPROVED** [review]
Looks good to me :D

**Comment by Kinerius** [comment]
image

Just to add more info on why it looks good for me, the performance difference with master is insignificant

**Comment by pravusjif** [comment]
By doing performance comparisons on [this other approach](https://github.com/decentraland/unity-renderer/issues/2433#issuecomment-1194156935) I found out that the first time we run the Performance Meter Tool with 30 seconds or more, we have a huge hiccup that affects its result. If we run it again after that in the same session, it doesn't happen.

The result I reported here of performance score 76 against 90 with this approach is not certain, since the new performance comparisons show this approach a lot more close to production's performance score.

**Comment by Kinerius** [comment]
>  I found out that the first time we run the Performance Meter Tool with 30 seconds or more, we have a huge hiccup that affects its result. If we run it again after that in the same session, it doesn't happen.

Yeah we have to fix that or change the score so it's based on the 99/50/1 percentiles, those reduce the noise a lot

**Comment by pravusjif** [comment]
In the end the https://github.com/decentraland/unity-renderer/issues/2132 and https://github.com/decentraland/unity-renderer/issues/978 issues haven't been solved by this PR.

- Black and white issue: it is only happening using graphics setting in ULTRA
- Bucket attached to player appearing out of bounds: this has been fixed for the first-time scene instantiation but if the scene is reloaded the bug is triggered... maybe it has something to fo with asset library asset reutilization.

Discovered at: https://github.com/decentraland/unity-renderer/pull/2811#issuecomment-1214669985

**Pull request merged**
