### PR TITLE
fix: null chat notification entries in rare occasions

### PR DESCRIPTION
**Pull request by lorux0**
## What does this PR change?

Fixes that sometimes we get an exception on the notification panel due the notification entry being null.
The problem was due objects in the pool getting messed up between friend requests and chat messages. There was only one `entryPool` field for both kind of pools. When an entry was getting released, the internal object pool's linked list was nesting two different type of objects in the same pool.
The fix consists on referring to the correct pool depending on the type of notification.

```
NullReferenceException: Object reference not set to an instance of an object
DCL.Chat.Notifications.MainChatNotificationsComponentView.AddNewChatNotification (DCL.Chat.Notifications.PublicChannelMessageNotificationModel model) (at Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/MainChatNotificationsComponentView.cs:163)
DCL.Chat.Notifications.ChatNotificationController.AddNotificationAsync (DCL.Interface.ChatMessage message, DCL.Chat.Channels.Channel channel, System.Threading.CancellationToken cancellationToken) (at Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/ChatNotificationController.cs:207)
UnityEngine.Debug:LogException(Exception)
Cysharp.Threading.Tasks.UniTaskScheduler:PublishUnobservedTaskException(Exception) (at Library/PackageCache/com.cysharp.unitask@c7eedf85c7/Runtime/UniTaskScheduler.cs:90)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTaskVoidMethodBuilder:SetException(Exception) (at Library/PackageCache/com.cysharp.unitask@c7eedf85c7/Runtime/CompilerServices/AsyncUniTaskVoidMethodBuilder.cs:53)
DCL.Chat.Notifications.<AddNotificationAsync>d__33:MoveNext() (at Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/ChatNotificationController.cs:213)
Cysharp.Threading.Tasks.CompilerServices.AsyncUniTaskVoidMethodBuilder:Start(<AddNotificationAsync>d__33&) (at Library/PackageCache/com.cysharp.unitask@c7eedf85c7/Runtime/CompilerServices/AsyncUniTaskVoidMethodBuilder.cs:110)
DCL.Chat.Notifications.ChatNotificationController:AddNotificationAsync(ChatMessage, Channel, CancellationToken)
DCL.Chat.Notifications.ChatNotificationController:HandleMessageAdded(ChatMessage[]) (at Assets/Scripts/MainScripts/DCL/Controllers/HUD/NotificationMessagesHUD/ChatNotificationController.cs:145)
DCL.Social.Chat.ChatController:AddMessages(ChatMessage[]) (at Assets/Scripts/MainScripts/DCL/Controllers/ChatController/ChatController.cs:429)
DCL.Social.Chat.WebInterfaceChatBridge:AddMessageToChatWindow(String) (at Assets/Scripts/MainScripts/DCL/Controllers/ChatController/WebInterfaceChatBridge.cs:50)
UnityEngine.GameObject:SendMessage(String, Object)
<ProcessMessages>d__19:MoveNext() (at Assets/Scripts/MainScripts/DCL/WorldRuntime/KernelCommunication/WebSocketCommunication/WebSocketCommunication.cs:292)
UnityEngine.SetupCoroutine:InvokeMoveNext(IEnumerator, IntPtr)
```

## How to test the changes?

1. Launch the explorer
2. Use the chat by sending and receiving messages
3. Receive friend requests so they are added in the notification panel
4. Keep using the chat until you get more than 30 notifications (preferrable 60+)
5. You should always see the chat notifications in the panel as expected without exceptions
6. Use the taskbar, should open the windows as expected when clicking the buttons

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

**Review by kwsskulinski — APPROVED** [review]
Chat notifications work as expected. No issues were found,

**Comment by lorux0** [comment]
@mikhail-dcl @sandrade-dcl @kwsskulinski changed the approach because the first approach was not working correctly

**Review by kwsskulinski — APPROVED** [review]
No issue has been observed.

**Review by sandrade-dcl — APPROVED** [review]

**Review by mikhail-dcl — APPROVED** [review]
Looks good to me

**Pull request merged**
