### PR TITLE
chore: store test results in junit format

### LINKED ISSUE #132: Add store_test_results to CircleCI and make it work
- [x] To create an XML that is parseable by CircleCI to display the checklist in human readable format

### PR DESCRIPTION
**Pull request by kuruk-mm**
Fix #132

## What does this PR change?

CircleCI only understands the JUnit report format, and we use NUnit, so I transform from NUnit to JUnit and store the results. 

## How to test the changes?

1. Go to failed test report at: https://app.circleci.com/pipelines/github/decentraland/unity-renderer/1354/workflows/40641dd4-f348-491d-9f09-bdcc469bac25/jobs/6369 (or see on this PR pipeline at "[temp] Make CI fail on purpose" commit)
2. See if everything is right

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

**Comment by menduz** [comment]
Awesome, I haven't seen XSLT since 2008. Diablo III first homepage was built with XSLT+XML

**Review by menduz — APPROVED** [review]

**Review by AjimenezDCL — APPROVED** [review]

**Comment by AjimenezDCL** [comment]
This is great!

**Comment by BrianAmadori** [comment]
Now we get insights over the tests runtime and more:
https://app.circleci.com/insights/github/decentraland/unity-renderer/workflows/build-deploy/tests?branch=chore%252Fstore-test-results&reporting-window=last-30-days

**Review by BrianAmadori — APPROVED** [review]
Approving, but we agreed on removing the tests results xml from artifacts right? Maybe we can do that before merging this PR.

**Comment by kuruk-mm** [comment]
> Approving, but we agreed on removing the tests results xml from artifacts right? Maybe we can do that before merging this PR.

Yes, but thinking a bit more further, I think it will be nice to have those because what you see in CircleCI is not the original file. So keeping the original file in CircleCI maybe has a use case. What do you think?

**Pull request merged**
