### PR TITLE
fix: removed link escaping when sending to kernel

### PR DESCRIPTION
**Pull request by davidejensen**
## What does this PR change?

Remove url escaping when sending to kernel

...

## How to test the changes?

1. Launch the explorer
2. Edit profile by adding and removing links
3. Check that there are no errors in console related to links
4. Check that links are saved properly

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### <samp>🤖 Generated by Copilot at 6be6dba</samp>

This pull request fixes a bug in the My Account HUD feature that caused double encoding of social link URLs. It removes redundant calls to `UnityWebRequest.EscapeURL` in `MyProfileComponentView.cs` and `MyProfileLinkListComponentView.cs`.

### CODE REVIEW

**Review by kwssbocian — CHANGES_REQUESTED** [review]
❌Adding and removing links results in them being saved and viewable in the profile card. However adding a link containing any of the allowed special characters results in error messages from kernel being shown in console. These errors are then shown each time upon change to the user profile (including account settings and equipped wearables). Errors stop appearing once the link with special characters is removed from the profile.
image
https://github.com/decentraland/unity-renderer/assets/110463715/455d96aa-b195-4a07-b787-d04cdb61d9d7

**Comment by davidejensen** [comment]
@kwssbocian by any chance is that happening in production as well?

**Review by popuz — APPROVED** [review]
works fine for me

**Comment by anicalbano** [comment]
:white_check_mark: Tested and working as expected on the new build. Video attached as evidence!

https://github.com/decentraland/unity-renderer/assets/139157886/a4af1c8c-2236-47e4-bbe4-918bc2ca3eed

**Pull request merged**
