### PR TITLE
feat: webGL compatible websocket wrapper

### PR DESCRIPTION
**Pull request by AjimenezDCL**
## What does this PR change?

We are adding a library that allows us to use websockets in webgl builds in the future.

## How to test the changes?

There are core changes here. Test everything thoroughly. Pay special attention to desktop builds.

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### <samp>🤖 Generated by Copilot at d62a2e8</samp>

This pull request replaces the WebSocketSharp library with the HybridWebSocket library for the RPC communication with the kernel. This improves the WebSocket compatibility and performance for WebGL builds. It also adds the meta files and assembly definitions for the new library and the quests panel HUD feature.

### CODE REVIEW

**Review by lorux0 — APPROVED** [review]

**Review by popuz — APPROVED** [review]
love it ❤️‍🔥 One entry point for both WebGL and Desktop will be very clean improvement.

**Review by kuruk-mm — APPROVED** [review]
Great work!

**Review by Kinerius — APPROVED** [review]
Naisu

**Review by kwsskulinski — APPROVED** [review]
No issues were detected.

**Pull request merged**
