### PR TITLE
chore: add main-realm

### PR DESCRIPTION
**Pull request by hugoArregui**
This PR:

- if FF is enabled, add 'main' as a realm, available for changerealm or jumping using the UI
- if FF is enabled, skip realm selection and use main
- use realm-provider service for hot scenes and explore realms (so main realm is included in the results)

### CODE REVIEW

**Review by lorux0 — APPROVED** [review]

**Review by pravusjif — CHANGES_REQUESTED** [review]
The client never starts rendering using this build...

Screen Shot 2023-10-05 at 20 13 08

**Review by pravusjif — APPROVED** [review]
My bad, it just took longer than usual for some reason.

**Comment by hugoArregui** [comment]
@pravusjif sorry, I didn't clarify, the service is only available for sepolia right now, I'm working on deploying it on prod

**Comment by pravusjif** [comment]
Uhmm, I'm measuring loading times but I think this PR heavily affects the loading time for the mainnet... I'll get back to you shortly

**Review by pravusjif — CHANGES_REQUESTED** [review]
* With this PR build the initial loading time for me is around 5min 24seconds
Screen Shot 2023-10-05 at 20 20 31

* With play.decentraland.org the initial loading time for me is 42~ seconds

**Comment by pravusjif** [comment]
> @pravusjif sorry, I didn't clarify, the service is only available for sepolia right now, I'm working on deploying it on prod

Oh OK cool then when that is deployed in prod, the loading time should be fixed right? let me know and I'll re-check and approve the PR if that's the case

**Comment by hugoArregui** [comment]
> > @pravusjif sorry, I didn't clarify, the service is only available for sepolia right now, I'm working on deploying it on prod
> 
> Oh OK cool then when that is deployed in prod, the loading time should be fixed right? let me know and I'll re-check and approve the PR if that's the case

Correct, I'll let you know! Thank you for trying it!

**Comment by hugoArregui** [comment]
@pravusjif the service is deployed in prod as well! do you want to give it another shot? Thanks!

**Review by pravusjif — APPROVED** [review]
Awsome, now the world loaded without problems!

**Review by anicalbano — APPROVED** [review]
✅ Reviewed and approved by dev and QA

**Pull request merged**
