### PR TITLE
fix: sdk7's hover interaction canvas showing when UI hidden

### PR DESCRIPTION
**Pull request by pbosio**
closes https://github.com/decentraland/unity-renderer/issues/4039

Steps to reproduce
    Enter the world.
    Press [U] to hide the UI.
    Press [U] again to show the UI.
    Hover interaction text should not be displayed

### CODE REVIEW

**Review by kwsskulinski — CHANGES_REQUESTED** [review]
Issue is not fixed. I am still able to see the hover interaction canvas while hiding and showing UI.

**Comment by Kinerius** [comment]
image

Not only its not fixed, it remains there, after showing the UI again

**Comment by pbosio** [comment]
> image
> 
> Not only its not fixed, it remains there, after showing the UI again

LOL that awkward moment when unity doesn't save your last changes to the prefab 😅
sorry! should be fixed now

**Review by kwsskulinski — APPROVED** [review]
Issue is fixed. There are no hover interaction canvas when the UI is hidden.

**Review by Kinerius — APPROVED** [review]

**Pull request merged**
