### PR TITLE
fix: old nft emote loading delay fix in the renderer

### PR DESCRIPTION
**Pull request by Antivortex**
## What does this PR change?

Renderer fix for old emotes long loading time, we decided to recreate the PR to include it to dev

Closes #3004

## How to test this change?

Ask anybody who has old NFT emotes (i.e. Davide) to test if they load fast and without issues. Test new NFT emotes that can be minted on Goerli in the Decentraland Builder.

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

**Comment by Antivortex** [comment]
> 



> Hey @Antivortex, could you write down the "**How to test the changes?**" for thi fix? Thanks!

Done

**Review by sandrade-dcl — CHANGES_REQUESTED** [review]
After I play an emote, this emote become freeze and I can't play another one:

image

Maybe it is already fixed with the latest changes on dev?

**Comment by Antivortex** [comment]
> After I play an emote, this emote become freeze and I can't play another one:
> 
> image
> 
> Maybe it is already fixed with the latest changes on dev?



> After I play an emote, this emote become freeze and I can't play another one:
> 
> image
> 
> Maybe it is already fixed with the latest changes on dev?

Yes, this branch is outdated, I updated it with latest dev which contains the fix to the issue you describe

**Review by sandrade-dcl — APPROVED** [review]

**Review by davidejensen — APPROVED** [review]
I can confirm can old emotes in production and new emotes in goerli load in the backpack as expected, but even in production they load fast as expected

**Pull request merged**
