### PR TITLE
fix: Unexpected backpack behaviours

### PR DESCRIPTION
**Pull request by sandrade-dcl**
## What does this PR change?
This PR fixes this issue: https://github.com/decentraland/unity-renderer/issues/2595

The backpack was loosing all the COLLECTIBLES wearables each time we did this steps:

1. Open the backpack
2. Change your shoes
3. Save
4. Notice your avatar has been corretly modified
5. Open the backpack again (do this step quickly after the previous one)
6. Change tour shoes to another ones
7. Save
8. Notice your avatar has been corretly modified
9. Open the backpack again (do this step quickly after the previous one)
10. Notice your avatar preview has lost all your custom wearables (if you go to the COLLECTIBLES tab, you won't see any wearable loadad there)

backpack-broken

## How to test the changes?
1. Go to: https://play.decentraland.zone/?renderer-branch=fix/unexpected-backpack-behaviours
2. Reproduce the steps described above.
3. Check the backpack works as expected and our COLLECTIONS are always being loaded correctly.
4. Check also the avatar preview is always being loaded with the correct equipped wearables.

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

**Review by pravusjif — APPROVED** [review]
I guess we can merge it since it works for fixing the problem but it looks like a patch and not the fix to the real problem, do we really need to create these 2 lists on demand and traverse them checking if the equipped wearables are the same ones that were the last owned wearables requested?

If we are correctly saving the profile locally and correctly updating the equipped wearables only once when we save the backpack changes then we shouldn't be needing this patch that re-checks everything later...

**Comment by sandrade-dcl** [comment]
> I guess we can merge it since it works for fixing the problem but it looks like a patch and not the fix to the real problem, do we really need to create these 2 lists on demand and traverse them checking if the equipped wearables are the same ones that were the last owned wearables requested?
> 
> If we are correctly saving the profile locally and correctly updating the equipped wearables only once when we save the backpack changes then we shouldn't be needing this patch that re-checks everything later...

Yeah, I agree. We're going to investigate this issue more deeply because it seems we have some inconsistencies with the profile inventory and we shouldn't have to update it manually. Meanwhile, this patch could be useful if we don't find a definitive solution before the next release 👍

**Review by lorux0 — APPROVED** [review]
looks good to me!

**Comment by lorux0** [comment]
> I guess we can merge it since it works for fixing the problem but it looks like a patch and not the fix to the real problem, do we really need to create these 2 lists on demand and traverse them checking if the equipped wearables are the same ones that were the last owned wearables requested?
> 
> If we are correctly saving the profile locally and correctly updating the equipped wearables only once when we save the backpack changes then we shouldn't be needing this patch that re-checks everything later...

yeah we decided to remove the `UserProfileModel.inventory` field because kernel was always sending an empty array, and that was triggering the update of an empty inventory which was the root of the problem.. i think this approach removes confusion and the complexity of the current code state

**Review by kwssbocian — CHANGES_REQUESTED** [review]
On my end issue does not appear to be fixed, at least not entirely. Launching the client with the fix/unexpected-backpack-behaviours branch with the wallet login and going to the Collectibles section in the backpack causes the interface to dissapear almost immediately. Issue seems to be fixed for the guest login though as I have observed no issues there.

image

**Review by kwssbocian — APPROVED** [review]

**Comment by sandrade-dcl** [comment]
> On my end issue does not appear to be fixed, at least not entirely. Launching the client with the fix/unexpected-backpack-behaviours branch with the wallet login and going to the Collectibles section in the backpack causes the interface to dissapear almost immediately. Issue seems to be fixed for the guest login though as I have observed no issues there.

This is another issue (already happening in prod) that will be managed in a separate ticket 👍 Thanks!

**Pull request merged**
