### PR TITLE
refactor: new data store

### PR DESCRIPTION
**Pull request by BrianAmadori**
## What does this PR change?
This PR replaces the ad-hoc approach we had for data stores to a generic locator approach.

* Moved `BaseVariable` types to a new assembly.
* Extracted `DataStore` modules to separate files (each file will be moved to their respective systems later).
* Moved stray variable instances to new data store modules (`DataStore_Common` and `DataStore_Realm`)
* Implemented basic `DataStore` service implementation with `Get` and `Set` methods.

When the `ServiceLocator` is ready, this system will be promoted to be a proper service.

## How to test the changes?

As this PR doesn't change core logic, it can be tested by ensuring that the build runs and tests pass.

https://play.decentraland.zone/?renderer-branch=refactor/new-data-store

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

**Review by AjimenezDCL — APPROVED** [review]
Great job!

**Review by Kinerius — APPROVED** [review]
Nice!

**Review by pravusjif — APPROVED** [review]
Tested build

**Review by sandrade-dcl — APPROVED** [review]
LGTM!!

**Pull request merged**
