### PR TITLE
fix: sign up call

### PR DESCRIPTION
**Pull request by AjimenezDCL**
Sign up button in the client was not relaunching with show_wallet url param. Also the button was subscribed twice.

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

## Test
Use this link
https://explorer-artifacts.decentraland.org/@dcl/explorer-website/branch/feat/seamless-login/?explorer-branch=fix/sign-up-call

Go as a guest, open the explore Menu and in the upper right corner, press on your profile and click "Sign In". Decentraland should be relaunched prompting you to sign with a wallet.
image

### <samp>🤖 Generated by Copilot at 0225d99</samp>

This pull request refactors the code for the profile HUD, improving the communication between the browser and the Unity renderer. It changes how the sign up page is opened from the `Get a name` button, and how the button logic is handled in the `ProfileHUDViewV2` and `ProfileHUDController` classes.

### CODE REVIEW

**Review by guidota — APPROVED** [review]
LGTM

**Review by popuz — APPROVED** [review]
nice catch 👍

**Review by Kinerius — APPROVED** [review]

**Review by kwsskulinski — CHANGES_REQUESTED** [review]
Launching the explorer by using the test link leads to the crash screen.
image
Using the automatic link launches the explorer, but the 'Sing In' button works the same as before- no instant prompt to login with wallet.

**Comment by AjimenezDCL** [comment]
> Launching the explorer by using the test link leads to the crash screen. image image
> 
> Using the automatic link launches the explorer, but the 'Sing In' button works the same as before- no instant prompt to login with wallet.

@kwsskulinski sorry! the link was malformed, now you should have it okay

**Review by kwsskulinski — APPROVED** [review]
No issues found.

**Pull request merged**
