### PR TITLE
fix: rethrow OperationCancelled exception to be caught upstream

### PR DESCRIPTION
**Pull request by AjimenezDCL**
The avatar loading was not rethrowing when cancelled and breaking some flows

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

**Review by BrianAmadori — APPROVED** [review]

**Comment by menduz** [comment]
Confirmed working on testing branch

**Comment by menduz** [comment]
Sadly it does not happen on the first time but it does in subsequent profile updates

**Comment by menduz** [comment]
It also happens when editing the avatar for a while. You can see in the screenshot that I spent around 10sec editing the avatar (therefore the HUD works)

Screen Shot 2022-04-24 at 12 39 42

**Comment by AjimenezDCL** [comment]
Gonna merge this, since it fixes some issues. Let's keep debuging #2152 with master or a new debuging branch.

**Pull request merged**
