### PR TITLE
feat: New Friend Requests feature integration

### PR DESCRIPTION
**Pull request by lorux0**
## What does this PR change?
Provides real working flows for the new Friend Requests feature.

**PRD:** https://www.notion.so/PRD-New-Friend-Requests-188555225272448f91f3eea5e84f1cd3

## How to test the changes?
**URL to test**: https://play.decentraland.zone/?renderer-branch=feat/friend-requests-integration&kernel-branch=refactor/add-timestamp-to-id

### Send a Friend Request
1. Open the passport of a non-friend user and click on the [ADD FRIEND] button.
2. This modal should appear:
image
3. Test all the flows of the modal (text max lenght validation, cancel button, click out of the modal, send button...)
4. Once you send the friend request you should see the different status of the modal: sending and error (if the request failed) / success (if the request was sent successfully):
image
image
5. After this, check that the friend request was effectively sent to the other user.

### Receive a Friend Request
1. You should see a notification like this when you receive a friend request from other user: 
image
2. You should also see the friend request entry in your list of friend requests:
image
3. If you click on any of them, this modal should open:
image
4. Test all the flows of the modal (profile button, decide later button, click out of the modal, reject button, confirm button...)

### Reject a Friend Request
1. If you reject a friend request, you should see the different status of the modal: rejecting and error (if the rejection failed) / success (if the rejection was sent successfully):
image
image
2. Notice the entry dissapeared from our requests list.
3. Also, notice that if you click on the notification that you received about this friend request, the modal won't open because the associated request was already rejected.

### Accept a Friend Request
1. If you confirm a friend request, you should see the different status of the modal: confirming and error (if the confirmation failed) / success (if the confirmation was sent successfully):
image
image
2. Notice the entry dissapeared from our requests list and the friend appears on your friends list.
3. Also, notice that if you click on the notification that you received about this friend request, the modal won't open because the associated request was already accepted.

## Missing things
The only thing that is currently missing for this new feature is the "[initial conversation](https://www.notion.so/decentraland/PRD-New-Friend-Requests-188555225272448f91f3eea5e84f1cd3#34547da8d5dc4eb7baeb05da10114f96)" that should be created after accepting a friend request. This is being currently implemented by dService team and we will test it separatelly once they have it done.

## Our Code Review Standards
https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

**Review by dalkia — COMMENTED** [review]
Found an edge case that may be worth to take a look at

1. User A sends a friend request
2. User B rejects it
3. User B sends a friend request
4. User B clicks on the old notification of User A request. He can now friend himself. This messes the UI temporarily, and User B sees that he is friend with User A. Closing the passport fixes this
5. User A still have the request from User B. User A accepts the requests, but User B does not appear on Friends list. This gets fixed with a reset

Given that notifications never dissapear, can we disable the onClick interaction of old notifications, like an old friend request?

https://user-images.githubusercontent.com/1999557/208923132-b0c3eacc-5fe8-4e67-9024-ba0d2be5818f.mp4

**Review by dalkia — APPROVED** [review]
Besides the edge case mentioned above, everything's looking good!

**Comment by lorux0** [comment]
> Found an edge case that may be worth to take a look at
> 
> 1. User A sends a friend request
> 2. User B rejects it
> 3. User B sends a friend request
> 4. User B clicks on the old notification of User A request. He can now friend himself. This messes the UI temporarily, and User B sees that he is friend with User A. Closing the passport fixes this
> 5. User A still have the request from User B. User A accepts the requests, but User B does not appear on Friends list. This gets fixed with a reset
> 
> Given that notifications dont dissapear immediately, can we disable the onClick interaction of old friend requests notifications?
> 
>  2022-12-21.10-39-36.mp4

thanks for the report! thats something we are already working on here: https://github.com/decentraland/unity-renderer/tree/fix/friend-requests-refinement

**Review by kwspgoliasz — DISMISSED** [review]
The core feature is functioning correctly, however, several issues of varying severities were found during testing. The issues are as follows:

- [x] A typo in the notification message displayed when cancelling the invitation: 

- [x] The spacebar interval does not switch to the new text line after reaching the edge of the message box: https://user-images.githubusercontent.com/110464313/210071652-bb3251cb-7161-40a3-97b0-976c7a39474c.mp4.

- [x] The letter limit is ignored if the invitation message has more than three lines: https://user-images.githubusercontent.com/110464313/210071778-8cb5082c-b9f8-46a5-a5e6-7d92dc05306f.mp4.

- [ ] DM's chat history is not displayed correctly: https://user-images.githubusercontent.com/110464313/210071816-267a5aab-189e-405a-bc5c-eab7079d08db.mp4.

- [ ] Accepting/rejecting a request via the passport doesn't turn off the invitation modal. This allows to reject/accept the invitation via the passport and then do the opposite via the modal, creating issues with the UI (ex. the user is listed as a friend in one of the passports, the next sent invitation is not displayed in the request tab until it's closed and reopened): https://user-images.githubusercontent.com/110464313/210072252-41e8757b-9fa4-4616-9226-e518502ba0a2.mp4, https://user-images.githubusercontent.com/110464313/210071933-6727c3c3-acd9-44e7-938e-6318376ee333.mp4.

- [x] Notification for previously added friend can be used to open the invitation modal on the sender's side: https://user-images.githubusercontent.com/110464313/210071881-c5d0cfd1-2b49-477e-a890-fcecc12f711b.mp4.

- [x] Using different friend request flows multiple times can randomly change the senders modal  with the receivers one, for example: cancel request modal is changed into accept/reject modal: https://user-images.githubusercontent.com/110464313/210071905-1a3b88da-cd97-4462-a943-561a5e2ffeea.mp4.

According to @lorux0 the last two issues should be dealt with after dservices implement their fixes.

**Comment by lorux0** [comment]
> * [ ]  The spacebar interval does not switch to the new text line after reaching the edge of the message box: https://user-images.githubusercontent.com/110464313/210071652-bb3251cb-7161-40a3-97b0-976c7a39474c.mp4.
We will set the receive/sent input field as multi-line, but for sending requests will remain like this because it is the standard behaviour of input fields and we dont have any setting to fix it.

> * [ ]  The letter limit is ignored if the invitation message has more than three lines: https://user-images.githubusercontent.com/110464313/210071778-8cb5082c-b9f8-46a5-a5e6-7d92dc05306f.mp4.
We did this on purpose because we dont have any scroll in the design. However we will confirm with UX/Product if we should add a scroll in the future.

> * [ ]  DM's chat history is not displayed correctly: https://user-images.githubusercontent.com/110464313/210071816-267a5aab-189e-405a-bc5c-eab7079d08db.mp4.
A kernel fix is required, not a renderer issue. The fix is in progress though.

> * [ ]  Accepting/rejecting a request via the passport doesn't turn off the invitation modal. This allows to reject/accept the invitation via the passport and then do the opposite via the modal, creating issues with the UI (ex. the user is listed as a friend in one of the passports, the next sent invitation is not displayed in the request tab until it's closed and reopened): https://user-images.githubusercontent.com/110464313/210072252-41e8757b-9fa4-4616-9226-e518502ba0a2.mp4, https://user-images.githubusercontent.com/110464313/210071933-6727c3c3-acd9-44e7-938e-6318376ee333.mp4.
We will need to confirm with product what is the best thing we can do in this case. Because there are some cases that may feel very weird/broken for the user. For example: you get the friend request popup opened and the peer accepts your request. Following the pattern, the popup will be automatically closed and we feel that the user will not understand it.

> * [ ]  Notification for previously added friend can be used to open the invitation modal on the sender's side: https://user-images.githubusercontent.com/110464313/210071881-c5d0cfd1-2b49-477e-a890-fcecc12f711b.mp4.
A kernel fix is required, not a renderer issue. The fix is in progress though.

We will work on the rest of the reported issues. Thanks!

**Review by kwssbocian — APPROVED** [review]
Feature implemented correctly.
✔️Send, receive, accept and reject friend request flows are working correctly.
Additionally the previous issues that were declared to be addressed within this PR have been fixed. No additional issues have been found.

**Pull request merged**
