### PR TITLE
feat: Report scene button on minimap hud

### PR DESCRIPTION
**Pull request by dalkia**
## What does this PR change?

Adds the option to report a scene using the minimap menu.

## How to test the changes?

1. Open the 3dots menu of the scene in the minimap. It will show a submenu with the report button
2. Clicking on it, will open a Google report form.
3. Scene location should be prepopulated

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

**Comment by RominaMarchetti** [comment]
@dalkia please check the Figma design [here](https://www.figma.com/file/eEsaueYji7mxejh8hlbu18/Map-V2?node-id=904%3A11189).

Things to have into account:
- [ ] The container must have the same width than the mini map. 
- [ ] Fix the margins between all the UI elements and the container.
- [ ] Increase the gap between the text and the switch element `Show scene UI` option.
- [ ] `Report` button goes bellow the `Show scene UI` option.
- [ ] There is a line between the `Show scene UI` and `report` options.
- [ ] The icon and text of `report` must be aligned to the left.
- [ ] Remove the black container background from `report` (it is hard to see because of the low contrast but I'm sure it is there XD)

**Review by RominaMarchetti — CHANGES_REQUESTED** [review]
@dalkia please check the Figma design [here](https://www.figma.com/file/eEsaueYji7mxejh8hlbu18/Map-V2?node-id=904%3A11189).

Things to have into account:
- [x] The container must have the same width than the mini map.
- [x]  Fix the margins between all the UI elements and the container.
- [ ]  Increase the gap between the text and the switch element Show scene UI option.
- [x]  Report button goes bellow the Show scene UI option.
- [ ]  There is a line between the Show scene UI and report options.
- [ ]  The icon and text of report must be aligned to the left.
- [ ]  Remove the black container background from report (it is hard to see because of the low contrast but I'm sure it is there XD)

**Review by kwssbocian — APPROVED** [review]
Feature appears to be implemented correctly.

✔️ Clicking the triple dots menu underneath the mini map opens up a submenu that contains ✔️ the Report Scene option.
✔️ Clicking on Report Scene opens up a report form through Google Forms with the scene location coordinates filled in.

✔️ The container has the same width as the mini map.
✔️ Margins between all the UI elements and the container are equal.
✔️ The gap between the text and the switch element Show scene UI option has been increased.
✔️ Report button is located below the Show scene UI option.
✔️ There is a line between the Show scene UI and report options.
✔️ The icon and text of report must are aligned to the left.

**Review by davidejensen — APPROVED** [review]
Niiice

**Review by RominaMarchetti — APPROVED** [review]

**Pull request merged**
