### PR TITLE
fix: seamless login

### PR DESCRIPTION
**Pull request by AjimenezDCL**
## What does this PR change?
Fixes issues in the seamless login flow.
...

## How to test the changes?

Go to https://play.decentraland.org/?explorer-branch=fix/seamless-login-bugs&ENABLE_SEAMLESS_LOGIN_VARIANT:ENABLED

Expected scenarios:
- New account (no profile in the catalyst, wallet or not) when seamless login is enabled shows the new ToS Popup and lands directly in the world
    - Reloading without accepting ToS shows  the popup again
    - Rejecting the ToS redirects to `decentraland.org`, going into the world again shows the ToS
    - Accepting To.
       - if guest user, opening a new session or clearing cache will clear everything and ToS popup will appear again
       - if wallet, as long as the profile is deployed (to be sure finish the tutorial or go to Genesis Plaza, change your name, your wearables, etc...), ToS wont appear again.
 - Old accounts (wallet with a profile deploed or guest with an on-going session in the browser) shouldnt show ToS popup
  

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### <samp>🤖 Generated by Copilot at 1ddbd73</samp>

This pull request adds some debugging logs to `renderer/sagas.ts` to investigate a profile bug, and simplifies the sign up logic in `session/sagas.ts` to improve the seamless login feature.

### CODE REVIEW

**Comment by dalkia** [comment]
Code is fine, but for some weird reason, people are white in this branch (not happening in zone)

`branch:`
image

`zone`:
image

**Comment by AjimenezDCL** [comment]
> Code is fine, but for some weird reason, people are white in this branch (not happening in zone)
> 
> `branch:` image
> 
> `zone`: image

Let me update the branch with dev, maybe that's the issue. I didnt change anything related to that

**Comment by dalkia** [comment]
@AjimenezDCL 

Fixed now! Approving :)

image

**Review by kwsskulinski — APPROVED** [review]
No issues have been found.

**Pull request merged**
