### PR TITLE
fix: duplicated sprites in UI atlases

### LINKED ISSUE #4209: Removed duplicated sprite in atlases
`FriendRequest` folder is added in two different atlases. Analyze which is the best atlas to keep it, taking batching & optimization in consideration.

Why? Because it causes an unneeded memory footprint.

Acceptance criteria:

- [ ] The friend request sprite assets should be included only in one sprite atlas.

### PR DESCRIPTION
**Pull request by lorux0**
## What does this PR change?

`Fixes #4209 `

Moved all the UI textures to `Common` folder.
Every subfolder in the UI have its own atlas containing its own sprites.

## How to test the changes?

1. Go to: https://play.decentraland.org/?explorer-branch=fix/duplicated-sprites-in-atlases
2. Navigate through all the UI
3. No missing icons in the UI should be missing

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

**Review by kwssbocian — CHANGES_REQUESTED** [review]
❌Realm choice screen on both webGL and desktop features two misplaced icons above the player count column.
image

**Review by mikhail-dcl — APPROVED** [review]
No code to review

**Comment by lorux0** [comment]
> ❌Realm choice screen on both webGL and desktop features two misplaced icons above the player count column. image

Good catch! Should be fixed now:
Screen Shot 2023-02-16 at 13 10 06

**Review by kwssbocian — APPROVED** [review]
✔️After additional fixes all icons appear to be placed correctly. No more issues have been found.

**Pull request merged**
