### PR TITLE
chore: update unity project version to unity2022.3.6f1

### PR DESCRIPTION
**Pull request by pravusjif**
* Updated whole project from `Unity 2021.3.22f1 LTS` to `Unity 2022.3.6f1 LTS`
* Updated UberPost shader based on URP `14.0.8`. Re-applying [our alpha value fix](https://github.com/decentraland/unity-renderer/pull/3578)
* Updated CharacterPreview prefab camera background color from white to black to improve avatars blending with the passport screen background
* As per 2022.3.6f1 the annoying "FMOD errors" in the WebGL build should've gone away 
* Updated CI images used
* Tried to replace the `RenderTargetHandle` usages (marked as `obsolete` since URP 13) with the new `RTHandle` class but couldn't get it to work. Since in URP 14.0.8 (the one used with Unity 2022.3) the old "obsolete" class still works, I'm leaving that implementation as it was. [I created an informative draft PR to tackle that in the future, since probably that change will be mandatory to update the URP version further.](https://github.com/decentraland/unity-renderer/pull/5562)

------------------------

### TESTING

This build should be tested as throroughly as a Release Candidate, and also adding:
* Creating a new avatar from scratch as a guest
* Creating a new avatar from scratch as a non-guest
* Checking if the popular scenes work/look the same way as in production (ICE Poker scene, Wonder Mine, GolfCraft, any other scene that contains video playing)

### TEST LINKS

* **Web**: https://play.decentraland.org/?explorer-branch=test/perf-profiling-unity2022.3.4f1
* **Web**: https://play.decentraland.zone/?explorer-branch=test/perf-profiling-unity2022.3.4f1
* **Desktop**: https://renderer-artifacts.decentraland.org/desktop/index.html?dcl://DESKTOP-BRANCH=test/perf-profiling-unity2022.3.4f1

### CODE REVIEW

**Comment by pravusjif** [comment]
the CI error was due to using cached libraries for Unity 2021.3.22 instead of the new version

**Review by anicalbano — APPROVED** [review]
✅ PR reviewed by QA. No issues where found on our checks.

**Comment by pravusjif** [comment]
I'll update with `dev` latest changes just before merging to `main`.

**Review by pbosio — APPROVED** [review]

**Review by sandrade-dcl — APPROVED** [review]
LGTM!

**Pull request merged**
