### PR TITLE
feat: glTFast integration

### LINKED ISSUE #2516: Integrate glTFast package
We need to integrate https://github.com/atteneder/glTFast and replace our current solution for loading GLTFs as it's 2 years old and contains many bugs and performance issues and is outdated in terms of supported features.

We need to do a quick implementation first to see if it covers our needs:

- [x] try glTFast in APK_GLTF_InteractiveTest and load our test GLBs
- [x] wrap the loader in a promise, so we can re-use the loader object to instantiate multiple game objects without reloading the gltf.
- [x] Dispose the loader when the ref count is zero, there shouldn't be any leak.
- [x] Plug the new promise into our system so the GLTF to be loaded uses this new loader instead of the old one.
- [x] inject an IMaterialGenerator to integrate our custom materials, both old and newly imported objects should look alike.

At this point, we can do an internal release to see if everything works fine.

- [x] Test in Unity Editor
- [x] Test webGL build
- [x] Test Desktop ( windows / macos )

Issues to be fixed before resuming

- [x] Some colliders are not working properly ( beers in genesis plaza are not being filled :( )
- [x] Avatar fails load
- [x] WebGL version seems stuck
- [x] GLTFs are not loading (we need to differentiate GLB and GLTF from the file from content server ) 
- [x] Materials shaders are not `DCL/Universal Render Pipeline/Lit` (Do we really need them?) 
- [x] Some PointerEvents are throwing null references
- [x] Avatar combiner ends up with incorrect material setup

After the tests and fixes we should refine this even further

- [x] Refactor any ugly implementation.
- [x] Create a feature flag to toggle the GLTF loader with the old one.
- [x] Test the new GLTF loader with the AB converter
- [x] Fix all directories and file handling to be case-insensitive
- [ ] Fix tests that fail when using GLTFast, now that its behind a feature flag they don't, but they will if we remove the old GLTF loader system
- [x] Check for performance and leaks from the wrappers

---

Next Steps

- [x] Reduce texture size for WebGL

https://github.com/decentraland/asset-bundle-converter
- [x] Integrate GLTFast with the AB Converter
- [x] Migrate the AB converter to its own repository

### PR DESCRIPTION
**Pull request by Kinerius**
## What does this PR change?

- [glTFast](https://github.com/atteneder/glTFast) package Integration.
- This includes [DracoUnity](https://github.com/atteneder/DracoUnity) which enables loading compressed GLBs, used by glTFast internally.
- glTFast was wrapped using AssetPromises
- All materials were converted to use `DCL/UniversalRenderPipeline/Lit` shader

Closes #2516

## How to test

This feature is best testable on Desktop:

[WebGL Test Link](https://play.decentraland.zone/?renderer-branch=feat/gltfast&DISABLE_ASSET_BUNDLES&DISABLE_WEARABLE_ASSET_BUNDLES&ENABLE_GLTFAST&)

No noticeable changes should be noticed, everything should look alike as how it works in production.

## Known Issues
- (WebGL) There are more out-of-memory crashes due to how gltf handles its loader, we are consuming a bit more memory than before.

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

**Review by kwspgoliasz — APPROVED** [review]
The feature appears to be implemented correctly, as no issues with the platform's mechanics were observed during the smoke test.

**Comment by sandrade-dcl** [comment]
### Visual issue found

**Using the PR build:**
image

**Using `dev` build:**
image

**Comment by sandrade-dcl** [comment]
Regarding the previous issue... see how the face of my avatar is being rendered:

image

**Comment by Kinerius** [comment]
> ### Visual issue found
> **Using the PR build: https://play.decentraland.zone/?renderer-branch=feat/gltfast&DISABLE_ASSET_BUNDLES&DISABLE_WEARABLE_ASSET_BUNDLES&ENABLE_GLTFAST** image
> 
> **Using `dev` build: https://play.decentraland.zone/?DISABLE_ASSET_BUNDLES&DISABLE_WEARABLE_ASSET_BUNDLES&ENABLE_GLTFAST** image

nice find, this might be related to the back face culling, I had my doubts when getting the information from the new materials since they have different properties

**Comment by sandrade-dcl** [comment]
I found this wearable that is being rendered different in this build than in prod:

**This build:**
image

**Prod:**
image

**Review by sandrade-dcl — CHANGES_REQUESTED** [review]
Code reviewed 👍 
Build tested -> Some visual issues found!

**Review by sandrade-dcl — APPROVED** [review]
Issues fixed! Good work!

**Review by pravusjif — CHANGES_REQUESTED** [review]
#### I've been testing the build extensively (always with `DISABLE_ASSET_BUNDLES&DISABLE_WEARABLE_ASSET_BUNDLES`) and unfortunately I found 4 problems:

1. Found 1 mesh that is rendered in prod but is not rendered with GLTFast
2. With GLTFast, in the Ice Poker The Stonghold (-100,127) I always get a memory crash soon after loading the scene. Without GLTFast I couldn't get it to crash even running around the poker tables inside the scene
3. In our Goerli hellmap some problems with the Ambient Occlusion can be clearly seen when using GLTFast
4. In our Goerli hellmap, there is a big difference with colors when using GLTFast, with GLTFast it appears like every color is a lot lighter

### Problems screencaps
#### 1. Mesh rendered in prod but not with GLTFast

Screen Shot 2022-09-20 at 17 34 57

Screen Shot 2022-09-20 at 16 19 23

#### 2. ICE Poker scene crashing with GLTFast

**WITH GLTFast**
https://play.decentraland.org/?renderer-branch=feat%2Fgltfast&DISABLE_ASSET_BUNDLES=&DISABLE_WEARABLE_ASSET_BUNDLES=&ENABLE_GLTFAST=&realm=dg&position=-100%2C128&island=I7a

**NO-GLTFast**
https://play.decentraland.org/?DISABLE_ASSET_BUNDLES=&DISABLE_WEARABLE_ASSET_BUNDLES=&ENABLE_GLTFAST=&realm=dg&position=-100%2C126&island=I7a
or
https://play.decentraland.org/?renderer-branch=feat%2Fgltfast&DISABLE_ASSET_BUNDLES=&DISABLE_WEARABLE_ASSET_BUNDLES=&realm=dg&position=-100%2C128&island=I7a

https://user-images.githubusercontent.com/1031741/191363325-a0f68148-ea2d-4890-adfe-d39d2f8e1f31.mp4

https://user-images.githubusercontent.com/1031741/191363362-5570d206-6f58-45f7-921e-dfa5b594f34c.mp4

Screen Shot 2022-09-20 at 16 50 59

Screen Shot 2022-09-20 at 16 51 25

Screen Shot 2022-09-20 at 16 51 15

Screen Shot 2022-09-20 at 16 51 40

Screen Shot 2022-09-20 at 16 51 49

#### 3. Ambient Occlusion problem with GLTFast branch but not in prod

https://user-images.githubusercontent.com/1031741/191364009-075b1cca-c9bc-4339-8c61-fe8dfed6951c.mp4

https://user-images.githubusercontent.com/1031741/191364074-59c0f585-4fbe-4dda-aa40-357f8e48711c.mp4

#### 4. Colors drastically lighter in GLTFast branch compared to prod

Screen Shot 2022-09-20 at 17 20 49

Screen Shot 2022-09-20 at 17 10 17

Screen Shot 2022-09-20 at 17 21 30

Screen Shot 2022-09-20 at 17 11 07

Screen Shot 2022-09-20 at 17 23 35

Screen Shot 2022-09-20 at 17 12 41

**I think this next screenshot shows that the GLTFast mesh materials are not using our usual shader, because of the missing Y clipping that Alex had implemented for this scene:**
Screen Shot 2022-09-20 at 17 24 32

Screen Shot 2022-09-20 at 17 11 22

Screen Shot 2022-09-20 at 17 25 13

Screen Shot 2022-09-20 at 17 11 32

Screen Shot 2022-09-20 at 17 26 15

Screen Shot 2022-09-20 at 17 11 56

**Comment by pravusjif** [comment]
Re-tested with latest changes:
- Lighter colors problem has been fixed
- Ambient occlusion problem has been fixed

**Review by pravusjif — CHANGES_REQUESTED** [review]
Re-tested with latest changes.

Fixes confirmed:
- Lighter colors problem has been fixed
- Ambient occlusion problem has been fixed

Persisting problems:
- Meshes not rendered with GLTFast but rendered with UnityGLTF at https://play.decentraland.org/?renderer-branch=feat%2Fgltfast&DISABLE_ASSET_BUNDLES=&DISABLE_WEARABLE_ASSET_BUNDLES=&ENABLE_GLTFAST=&realm=dg&position=-17,4
(remove `&ENABLE_GLTFAST=` to see the meshes rendering fine)

- Still experiencing a quick crash when entering ICE poker scene [with GLTFast](https://play.decentraland.org/?renderer-branch=feat%2Fgltfast&DISABLE_ASSET_BUNDLES=&DISABLE_WEARABLE_ASSET_BUNDLES=&ENABLE_GLTFAST=&realm=dg&position=-100%2C128) compared to [not using GLTFast](https://play.decentraland.org/?renderer-branch=feat%2Fgltfast&DISABLE_ASSET_BUNDLES=&DISABLE_WEARABLE_ASSET_BUNDLES=&realm=dg&position=-100%2C128) (make sure comms loaded lots of avatars around the player to reproduce the issue)

**Comment by Kinerius** [comment]
@pravusjif the crash on ICE poker is completely normal since GLTFast is consuming a bit more of memory since we are still not reducing the texture size.

**Comment by pravusjif** [comment]
> @pravusjif the crash on ICE poker is completely normal since GLTFast is consuming a bit more of memory since we are still not reducing the texture size.

Uhmmm ok, then we'll add texture compression in another PR before turning the GLTFast feature flag ON by default right? to avoid having tons of complaints from DG and casino userers.

--------------------

Then the only problem that needs to be fixed is the mesh that is not rendered with GLTFast

**Comment by Kinerius** [comment]
> Then the only problem that needs to be fixed is the mesh that is not rendered with GLTFast

Yes! Its on the backlog, I wont merge this until everything is confirmed to be working properly :D

**Review by kwspgoliasz — CHANGES_REQUESTED** [review]
The feature appears to be implemented mostly correctly. No major issue were found besides the crashes which are supposed be addressed in a separate PR.
A couple of medium severity issues were found, which could have a negative effect on the platform. The found issues are:

- [ ] The avatars can be sometimes seen T-posing during the spawn animation: https://user-images.githubusercontent.com/110464313/205062680-b5770659-a8b1-497e-b83a-83abff7e0e8e.mp4.

- [ ] The robots are not reacting to interaction (the squares do not change color) in the goerli testing scene related to SDK OnPointerEvent Interactions check: https://user-images.githubusercontent.com/110464313/205062734-c262685d-80c7-42bc-8af2-566958b2dfea.mp4.

**Review by pravusjif — APPROVED** [review]
I'm giving my approval to avoid blocking this PR, the remaining things to tackled are the ones mentioned by @kwspgoliasz https://github.com/decentraland/unity-renderer/pull/2534#pullrequestreview-1200980941

**Review by kwspgoliasz — CHANGES_REQUESTED** [review]
The update had no negative influence on basic platform mechanics. Previously found issues were all fixed.
An additional issue with NFT wearables not getting displayed was found. The issue was reproduced only for one item. The issue did not occur on the production branch.
#2534_gltfast
#2534_Prod

**Pull request merged**
