### PR TITLE
feat: chat history iteration with up & down keys

### LINKED ISSUE #1666: Pressing UP / DOWN in the chat input should iterate on chat history
UP and DOWN keys need to cycle through the chat messages submitted by the player. If none, nothing happens.

Acceptance Criteria
- [x] Pressing UP fills input with previous message if exists
- [x] Pressing DOWN shows the next record on the history. If none, goes empty

### PR DESCRIPTION
**Pull request by lorux0**
## What does this PR change?

`Closes #1666 `

Press `UP arrow key` or `DOWN arrow key` to set the previous messages sent in the chat input field.

## How to test the changes?

1. Send any message in the chat
2. Pressing `UP arrow key` the last message should be set in the input field
3. Keep sending messages
4. When `UP arrow key` or `DOWN arrow key` should iterate over the whole chat history
5. The last history iteration should be filled with an empty text
6. Messages should not be duplicated in the history

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

**Review by davidejensen — CHANGES_REQUESTED** [review]
I've encountered 2 problems, up and down have the same order of cycling, in example if I have the following list of messages:
* Hi 
* how are you
* I'm fine
* nice
if I press arrow up i get "nice" if i press it again i get "I'm fine" if I press arrow down I'm expecting to get "nice" but instead I get "how are you", if I press it again it starts working properly.

If I send a white space message it is not sent in the chat but it is saved in the previous messages

**Comment by lorux0** [comment]
> I've encountered 2 problems, up and down have the same order of cycling, in example if I have the following list of messages:
> 
> * Hi
> * how are you
> * I'm fine
> * nice
>   if I press arrow up i get "nice" if i press it again i get "I'm fine" if I press arrow down I'm expecting to get "nice" but instead I get "how are you", if I press it again it starts working properly.
> 
> If I send a white space message it is not sent in the chat but it is saved in the previous messages

Im going to check the cycling order.
About the white space, i implemented a white space on purpose for the last item in the cycle. Perhaps is kind of confusing. I found it useful to have if you dont want to use any of the messages in the cycle. I will confirm this either way.

**Review by davidejensen — APPROVED** [review]
Looks good now, thanks!

**Review by AjimenezDCL — APPROVED** [review]
Approving with a small concern

**Pull request merged**
