### PR TITLE
fix: sdk7 reduce time of `SendCrdt` processing

### PR DESCRIPTION
**Pull request by pbosio**
## What does this PR change?
reduced time consumption on `SendCrdt` call
from a base (in best scenario) of ~3/4 milliseconds to 0 milliseconds
removed calls to `UniTask.WaitWhile` and `UniTask.WaitUntil` since they were taking lot of time plus they were generating memory allocation

related to issue: https://github.com/decentraland/sdk/issues/932

## How to test the changes?
all scenes sdk6 and sdk7 should load and work correctly

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### <samp>🤖 Generated by Copilot at 7b12575</samp>

This pull request optimizes the `SendCrdt` method for scene synchronization and improves the code style of the `ParseScenePortableExperienceFeatureToggles` method in `SceneControllerServiceImpl.cs`.

### CODE REVIEW

**Review by pravusjif — APPROVED** [review]
Tested at https://sdk-test-scenes.decentraland.zone/?position=77%2C-4&explorer-branch=fix%2Fsd7-sendcrdt-performance&realm=LocalPreview without a problem

**Comment by anicalbano** [comment]
✅ Scenes working as expected

**Review by anicalbano — APPROVED** [review]
✅ All scenes working as expected

**Review by kwssbocian — APPROVED** [review]
✔️SDK scenes working without issues. No noticeable changes in loading or behavior observed.

**Pull request merged**
