### PR TITLE
feat: backpack throttling

### PR DESCRIPTION
**Pull request by Kinerius**
## What does this PR change?

- Limited the amount of Thumbnail that load concurrently to 10.
- Limited the number of Wearables that can be shown to 3 rows and X columns ( where X is based on the screen size )
- If the Wearables are higher than the limit that can be shown, pagination is shown.

- Merged NFTItemToggle prefab variants into one, the variance is now driven by skins defined by `NFTItemToggleSkin` ScriptableObjects
- Removed the CollectionContainer prefab as it has no purpose now, the base script still remains and its called `ItemToggleContainer` 

- The ThumbnailManager manages the queue for the loading of the Textures, those textures are being cached and never get destroyed, we might have to limit or change this in the future.

## How to test the changes?

- Open the backpack, and check that changing the resolution also changes the number of wearables that can be shown. (the shirts section is the one with the most wearables)
- Check that the pagination appears and disappears when changing wearable sections.
- Check that the pagination works correctly, and has sound feedback and subtle animations.

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

**Review by sandrade-dcl — CHANGES_REQUESTED** [review]
I'm having this visual issue the first time I open the backpack:

image

Once I change the size of the browser window, it is fixed.

### Steps to reproduce
1. Enter the world (in my case it has been in the position 100,100)
2. Press directly `I` to open the backpack
3. Notice the gap between the wearables grid and the avatar preview.

**Comment by Kinerius** [comment]
The gap issue should be fixed, also I've fixed the reparenting of all the explore UI so this fixes the initial hiccup

**Review by sandrade-dcl — APPROVED** [review]
Now it is working perfectly, good work! And thanks for the fix about the parent setting of the UIs inside the StartMenu 💯

**Comment by RominaMarchetti** [comment]
@Kinerius this is looking amazing. There are still few to do:

- [ ] The size of the numbers must be the same than the buttons `randomize` and `done`.
- [ ] The font style must be Inter bold for all the numbers.
- [ ] The color of the non selected numbers must be #161518
- [ ] Adjust the `pixels per unit` in the image component of the white container for the arrow buttons. They look too rounded now. Try with a bigger number than 2 (2.5 or 3).

**Review by kwspgoliasz — CHANGES_REQUESTED** [review]
The feature appears to be implemented correctly.
Each section of the pagination gets highlighted and is accompanied by a sound.
The pagination properly disappears and reappears depending on whether it is required.
The number of visible wearables also changes accordingly to the size of the screen.

However, some small issues regarding the pagination were observed during the testing. The issues are:

1. Issues with the pagination when changing the screen size while being inside of the backpack - this issue results in either one of the icons getting hidden beneath another one, or the space between the number icon and the arrow being too large. The issue stops occuring after the specific backpack section is reloaded: https://user-images.githubusercontent.com/110464313/184887233-3cc957e3-384d-461c-8ff0-7ad4dd676f1f.mp4.

2. The arrow icon stays highlighted after getting clicked on: https://user-images.githubusercontent.com/110464313/184887280-f502876d-47c0-47de-b3ef-27511ec26984.mp4.

**Review by kwspgoliasz — CHANGES_REQUESTED** [review]
The features are implemented correctly, however, the issues with the pagination still occur. Additionally, a new issue with the icons was found.

1. After changing the size of the screen the icons are getting either hidden beneath one another, or the space between the number icon and the arrow icon becomes too large.
This is especially noticeable when the screen is small enough for there to be at least 4 sections to switch between - https://user-images.githubusercontent.com/110464313/185341895-51bc7f1a-ec7b-428e-9fd8-35c47a753ca5.mp4.

2. The right arrow icon still gets permanently highlighted after getting clicked on. The highlight has a pale grey color. In contrast, after the fixes, no highlighting is implemented for the left arrow - https://user-images.githubusercontent.com/110464313/185341680-fb016891-eaf1-462f-82ab-e5ae115afb01.mp4.

3.  In the Accessories section of the backpack, the arrow icons are displayed in the tabs with no items, such as mask, hat, helmet and top head - https://user-images.githubusercontent.com/110464313/185341643-9c009384-0232-4248-be9b-79609cfad72e.mp4.

**Comment by RominaMarchetti** [comment]
@Kinerius the container of the arrows now doesn't look as rounded as it should be.

- [ ] Check that the asset is `Container12` and the pixel per unit 2.5, for both: arrows an numbers.
- [ ] The highlight animation for the arrows is not consistent. The left arrow is ok considering it should just be a scale animation. Remove the color animation in the right arrow.
- [ ] The margin between sections and items is not correct. Now there is a huge gap while it should be the same than in production.
Screenshot 2022-08-18 at 10 46 49

**Review by kwspgoliasz — CHANGES_REQUESTED** [review]
The features appear to be implemented correctly. All of the previously mentioned issues were fixed, however, a new issue with the pagination not displaying correctly was found.
When entering the backpack for the first time after launching the game, the pagination numbers flicker when entering a new tab for the first time: https://user-images.githubusercontent.com/110464313/187388888-dd85a354-7fd3-469c-acb9-0a6ebe052216.mp4.
The issue occurs only when entering a specific backpack tab/section for the first time after starting a new session.

**Review by kwspgoliasz — APPROVED** [review]
The feature appears to be implemented correctly. Neither of the previously found issues occur anymore.

**Pull request merged**
