### PR TITLE
fix: avatar shape reparenting

### LINKED ISSUE #3088: Bug on movement and facing of other avatars
### What happened?

In all realms with a large crowd

what my avatar sees
* some avatars are running but backward
* some avatars are running  sideways
* some avatars are at a 45-degree angle

### Steps to reproduce

Try visiting places with crowded areas

(Note: sometimes this occurs randomly)

### Operating System

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36

### Wallet

Metamask

### CPU

Ryzen 5 CPU

### GPU

ANGLE (NVIDIA, NVIDIA GeForce GT 710 Direct3D11 vs_5_0 ps_5_0, D3D11) 512MB

### RAM

32GB

### Kernel Version

1.0.0-3091217358.commit-6c7ec91

### Unity Version

1.0.54128-20220919201839.commit-6faaa73

### Realm

dg

### NameTag

JimSedric

### PR DESCRIPTION
**Pull request by Kinerius**
## What does this PR change?

Fixes some avatars moonwalking due to a recent change that re-parents the avatar shape while its being loaded to avoid scaling errors.

Fixes #3088

## How to test the changes?

See other avatars running around, all of them should be facing the correct direction.

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

**Comment by Kinerius** [comment]
After separating the avatarContainer from the avatarRevealerContainer now it seems that the bounds are not being calculated correctly.

https://user-images.githubusercontent.com/7646450/191609082-e55a286e-380b-4164-b7f9-a05df30e3b82.mp4

**Review by kwspgoliasz — APPROVED** [review]
The feature appears to be implemented correctly, as no issues with avatar movement was observed.

**Review by kwspgoliasz — CHANGES_REQUESTED** [review]
The feature requires additional fixes, as the latest update introduced some additional issues.
From the user's perspective, not only are the avatars constantly T-posing, they're also sliding when moving around - https://user-images.githubusercontent.com/110464313/191926833-9c4ec4a8-665e-4df0-8f98-e2612a4f3356.mp4.

Moreover, the preview for the avatar does not load in the backpack, which results in the player being unable to change their wearables, or create a new avatar - https://user-images.githubusercontent.com/110464313/191930180-86c1a1bb-2eff-41c7-b4bb-6b6f122e3c19.mp4.

**Review by kwspgoliasz — CHANGES_REQUESTED** [review]
The fixes related to the functionality of avatar movements appear to be implemented correctly.
Neither moonwalking, nor t-pose sliding was observed during the tests, however, the bug causing the flickering of facial features is still present.
The issue can be observed on random avatars, especially at crowded locations such as Ice Poker or Genesis Plaza. The scale of the flickering differs between avatars - https://user-images.githubusercontent.com/110464313/191986105-7997e893-7961-4f19-af58-745e181a9e83.mp4.

**Pull request closed without merging**
