### PR TITLE
feat: SDK7 scene boundaries checker integration

### PR DESCRIPTION
**Pull request by pravusjif**
https://github.com/decentraland/unity-renderer/issues/3494

- Integrated `GltfContainer`, `MeshRenderer` and `MeshCollider` components to entity `MeshesInfo` to automatically work with current Scene Bounds Checker.

### CODE REVIEW

**Comment by nearnshaw** [comment]
@pravusjif   what about NFTShape, is it also possible to track this component with the same mechanics?

**Review by pbosio — COMMENTED** [review]
Could we discuss about this implementation? I don't think using `entity.meshesInfo` is a good idea

**Comment by pravusjif** [comment]
> Could we discuss about this implementation? I don't think using `entity.meshesInfo` is a good idea

Not using meshesinfo would require a big refactor because MeshesInfo already calculates the merged bounds of meshes and gets the collection of renderers, colliders, etc. but sure let's look for another approach if you like.

**Comment by pravusjif** [comment]
We'll be going with a different approach.

**Comment by pravusjif** [comment]
1. Implement this approach using old hacky/messy SBC
2. Have SBC working in prod for SDK7 scenes
3. Implement new clean SBC for SDK7 scenes removing the hacky stuff.

**Pull request closed without merging**
