### PR TITLE
fix: hot-reload for new files

### PR DESCRIPTION
**Pull request by kuruk-mm**
## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### <samp>🤖 Generated by Copilot at d77847b</samp>

Added a feature to reload scenes with fresh data from the content server in `parcelSceneManager.ts`. This helps with debugging and updating scenes.

### CODE REVIEW

**Comment by nearnshaw** [comment]
I'm running some tests.  Overall it works as intended, but there are cases when it doesn't. Also it's very slow, it often takes more than a minute from when I drag a builder model to when I see it in the preview. That's almost as slow as a manual reload 😐 

Here it worked acceptably fast:
https://github.com/decentraland/unity-renderer/assets/3507907/0b1dcffc-42d8-4a8c-8dda-5a55747838db

Here it worked but it was slow:
https://github.com/decentraland/unity-renderer/assets/3507907/ce376ed5-da6b-45dc-ab29-75b4de836278
(I added a blue tree, the recording just missed the first action, it takes over a minute to appear)

Here the item I added never appeared:
https://github.com/decentraland/unity-renderer/assets/3507907/a15cd14c-358c-424c-ae21-8cfdc663151e
(I didn't keep recording, but I waited several minutes. Then tried moving items, duplicating other items. Those things worked, but this item I added here didn't appear till I did a manual reload)

Sometimes the ground stays orange

**Comment by kuruk-mm** [comment]
> I'm running some tests. Overall it works as intended, but there are cases when it doesn't. Also it's very slow, it often takes more than a minute from when I drag a builder model to when I see it in the preview. That's almost as slow as a manual reload 😐
> 
> Here it worked acceptably fast: https://github.com/decentraland/unity-renderer/assets/3507907/0b1dcffc-42d8-4a8c-8dda-5a55747838db
> 
> Here it worked but it was slow: https://github.com/decentraland/unity-renderer/assets/3507907/ce376ed5-da6b-45dc-ab29-75b4de836278 (I added a blue tree, the recording just missed the first action, it takes over a minute to appear)
> 
> Here the item I added never appeared: https://github.com/decentraland/unity-renderer/assets/3507907/a15cd14c-358c-424c-ae21-8cfdc663151e (I didn't keep recording, but I waited several minutes. Then tried moving items, duplicating other items. Those things worked, but this item I added here didn't appear till I did a manual reload)
> 
> Sometimes the ground stays orange

I pushed some fixes. It's working very well on my computer without any significant delay.

**Comment by nearnshaw** [comment]
There's a noticeable improvement I think. The delays are inconsistent, tho, so there could be an element of luck. Sometimes it's pretty fast, sometimes takes a while.
It could be related to how the builder fetches the models, maybe it tries to show them before the model is downloaded, which could explain the orange floor. I notice at least that sometimes the model in the Babylon editor also takes a bit of time (tho much less)

This time it took long like in the previous tests
https://github.com/decentraland/unity-renderer/assets/3507907/150a3d2a-aa17-487a-b7bd-1d3d180b1580

Adding a cube with code:
It's quite a bit faster, the orange floor is a bit of a mystery tho.
https://github.com/decentraland/unity-renderer/assets/3507907/420c70c1-1661-4e05-bd08-f863af5ba7bd

**Comment by kuruk-mm** [comment]
> There's a noticeable improvement I think. The delays are inconsistent, tho, so there could be an element of luck. Sometimes it's pretty fast, sometimes takes a while. It could be related to how the builder fetches the models, maybe it tries to show them before the model is downloaded, which could explain the orange floor. I notice at least that sometimes the model in the Babylon editor also takes a bit of time (tho much less)
> 
> This time it took long like in the previous tests https://github.com/decentraland/unity-renderer/assets/3507907/150a3d2a-aa17-487a-b7bd-1d3d180b1580
> 
> Adding a cube with code: It's quite a bit faster, the orange floor is a bit of a mystery tho. https://github.com/decentraland/unity-renderer/assets/3507907/420c70c1-1661-4e05-bd08-f863af5ba7bd

Which OS are you using and what are the PC specs? I'm going to test on that OS.

I didn't have significant delays like you showed to me.

A video from my side:
https://github.com/decentraland/unity-renderer/assets/12563266/8a846083-0981-450b-86f9-59b1ed8beaea

**Review by nearnshaw — APPROVED** [review]

**Comment by nearnshaw** [comment]
This last build works perfectly well for me ❤️ 

https://github.com/decentraland/unity-renderer/assets/3507907/f6e27565-f16c-4bb6-b39e-8c936911d71b

**Pull request merged**
