### PR TITLE
fix: asset bundles converter gltfs dependencies

### PR DESCRIPTION
**Pull request by pravusjif**
Something broke when we implemented GLTFs multi-threadding loading and in some cases GLTFs are trying to be loaded before their external dependencies, thus triggering the `GLTFSceneImporter - Error - Buffer file not found` that breaks lots of GLTFs conversion, as described at https://github.com/decentraland/asset-bundle-converter/issues/1.

- [x] Fix isolated assets dumping
- [x] Fix affected assets when dumping the whole scene

### 1: Converting problematic scene with pre-multithreadding commit
1. In unity-renderer local repo move to the pre-multithreadding commit (`7d22053c23bf35fb3607632db57a918ee1181bc2`)
2. Convert one of the problematic scenes by calling the conversion in batch mode from the terminal (change path to your unity app and unity-renderer project): `/Applications/Unity/Hub/Editor/2020.3.0f1/Unity.app/Contents/MacOS/Unity -batchmode -projectPath "/Users/pravus/git/unity-renderer/unity-renderer" -batchmode -executeMethod DCL.ABConverter.SceneClient.ExportSceneToAssetBundles -sceneCid "QmNyiG9QRKraLxvijvT88EJZTrw6PkBANb3yhrFtzHuxRV" -output "/Users/pravus/git/unity-renderer/unity-renderer/AssetBundles"` (one of the affected scenes is https://peer.decentraland.org/content/entities/scene?pointer=-8,100 so we used the scene id from there)
3. After the scene conversion finishes, backup all the visual test resulting images you'll see at `unity-renderer/TestResources/VisualTests/CurrentTestImages/ABConverter/`, to compare those later with the conversion done with this PR's branch.
4. After backuping them, delete those visual test resulting images just in case

### 2: Converting problematic scene with this PR and comparing visual test images
1. In unity-renderer local repo move to this branch latest commit (`fix/AssetBundlesConverterGLTFsDependencies`)
2. Convert the problematic scene by calling the conversion in batch mode from the terminal (change path to your unity app and unity-renderer project): `/Applications/Unity/Hub/Editor/2020.3.0f1/Unity.app/Contents/MacOS/Unity -batchmode -projectPath "/Users/pravus/git/unity-renderer/unity-renderer" -batchmode -executeMethod DCL.ABConverter.SceneClient.ExportSceneToAssetBundles -sceneCid "QmNyiG9QRKraLxvijvT88EJZTrw6PkBANb3yhrFtzHuxRV" -output "/Users/pravus/git/unity-renderer/unity-renderer/AssetBundles"`
3. After the scene conversion finishes, compare all the visual test resulting images you'll see at `unity-renderer/TestResources/VisualTests/CurrentTestImages/ABConverter/` to the ones you backed up from the pre-multithreadding commit conversion. You have to preview them and see that they look the same (or almost exactly the same. Some of them that don't have the same file size, it could be due to lighting)

### CODE REVIEW

**Review by pbosio — APPROVED** [review]
any chance you could remove this line also? since it's not used at all :)
https://github.com/decentraland/unity-renderer/blob/master/unity-renderer/Assets/Scripts/MainScripts/DCL/Controllers/WebRequest/Interfaces/WebRequestAsyncOperation.cs#L78

**Review by Kinerius — APPROVED** [review]
LGTM!

**Comment by lorux0** [comment]
happens to me that on this branch compared to `7d22053c23bf35fb3607632db57a918ee1181bc2` i get less amount of ABs converted but the amount of visual tests is higher

**Comment by pravusjif** [comment]
The commit from this PR breaks the conversion of the example scene: https://github.com/decentraland/unity-renderer/pull/2240/files

**Comment by pravusjif** [comment]
I'm closing this PR since it's been stale/idle for more than 9 months now.

The initial problem tackled by this PR (and [not completely solved](https://github.com/decentraland/unity-renderer/pull/2219#pullrequestreview-976099452)) should be re-evaluated and if it's still happening a new solution should be implemented based on the current state of the unity asset bundles converter project.

**Pull request closed without merging**
