### PR TITLE
fix: support for overlapping avatar modifier areas

### PR DESCRIPTION
**Pull request by dalkia**
## What does this PR change?

Overlapping modifier areas generates a wrong behavior. Areas turn on and off the modifier even though the user is still inside at least one of the areas. This implementation solves the overlapping issue.

More info here: https://decentralandteam.slack.com/archives/C01QVR7TJK1/p1660333541371069

## How to test the changes?

1. Go to https://play.decentraland.zone/?renderer-branch=fix/overlap-avatar-modifier-areas&NETWORK=mainnet&position=-74,-99. There are some overlapping areas deployed in that scene, same as in this video

https://user-images.githubusercontent.com/1999557/185384451-578b9f31-bb6c-40b5-8c73-165b46fa495c.mp4

2. Check that your character is modified correctly

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### CODE REVIEW

**Comment by menduz** [comment]
@dalkia awesome!! Upon you finish can we have an ADR explaining how this should behave from the PoV of somebody that should implement it from scratch?

**Comment by dalkia** [comment]
> @dalkia awesome!! Upon you finish can we have an ADR explaining how this should behave from the PoV of somebody that should implement it from scratch?

@menduz sure thing! Once this gets merged I ll get into the ADR

**Review by davidejensen — APPROVED** [review]
👍

**Review by kwspgoliasz — APPROVED** [review]
The issue appears to be fixed. No overlapping was observed while moving between the scene areas.

**Pull request merged**
