### PR TITLE
fix: Changed audio clip import settings to minimize size

### PR DESCRIPTION
**Pull request by Landeplage**
Many sounds were forced to mono. All sounds brought down to 80% quality.

Issue #1502

## What does this PR change?

Reduces audio asset file sizes from 12.4 MB to 7.0 MB by forcing some sounds into mono and reducing the quality of all assets to 80%.

...

## How to test the changes?

1. Go to [test branch playtest link.](https://play.decentraland.zone/?renderer-branch=fix/audio-asset-size-minimize)
2. Listen to see if the audio still has acceptable quality.

### CODE REVIEW

**Comment by Suduck** [comment]
Hi there! Sorry for the dealy, can you please, update from master and change the builder clips in the new folder DCLPlugins/BuilderInWorld, Let me know and I will accept again

**Review by Suduck — CHANGES_REQUESTED** [review]
Hi there! Sorry for the dealy, can you please, update from master and change the builder clips in the new folder DCLPlugins/BuilderInWorld, Let me know and I will accept again

**Comment by Landeplage** [comment]
@Suduck Done. Looks like the import settings were preserved. Merged master into the branch and changed three sounds to mono, saving a few kB.

**Review by Suduck — APPROVED** [review]
Thank you very much for the changes! Looks good to me!

**Review by BrianAmadori — APPROVED** [review]

**Pull request merged**
