### PR TITLE
feat: show going to events in events section

### PR DESCRIPTION
**Pull request by davidejensen**
## What does this PR change?

Fix #https://github.com/decentraland/growth/issues/99

Adds a section displaying the "Going to" events in the events panel

...

## How to test the changes?

1. Launch the explorer
2. Go to the events section in the menu
3. Verify that after the highlighted events section the Going section appears
4. Verify that when you have events flagged as going to they appear in that section

## Our Code Review Standards

https://github.com/decentraland/unity-renderer/blob/master/docs/code-review-standards.md

### <samp>🤖 Generated by Copilot at 9f7445b</samp>

Refactored the events subsection of the explore feature to match the UI order. Changed the order of `view.Set*Events` calls in `EventsSubSectionComponentController.cs` accordingly.

### CODE REVIEW

**Review by Kinerius — CHANGES_REQUESTED** [review]
After clicking on an event to mark it that you want to go, the "going to" list is not updated, It gets updated after closing the explore view and opening it again. 

Im not sure if that's the intended behavior, doing the same thing but inverted is the same, you mark an event that you don't want to go and it doesn't disappear from that list instantly.

**Comment by davidejensen** [comment]
> After clicking on an event to mark it that you want to go, the "going to" list is not updated, It gets updated after closing the explore view and opening it again.
> 
> Im not sure if that's the intended behavior, doing the same thing but inverted is the same, you mark an event that you don't want to go and it doesn't disappear from that list instantly.

for the first point it's fixed in https://github.com/decentraland/unity-renderer/pull/4638 
for the second it's a wanted thing untill you refresh so that you can re-go to if you clicked by mistake

**Comment by davidejensen** [comment]
@kwssbocian hi, thanks for the feedback, I just merged dev in this branch, it should all be fixed as soon as CI finishes

**Review by Kinerius — APPROVED** [review]
All good!

**Pull request merged**
