### PR TITLE
style: BiW shortcut

### PR DESCRIPTION
**Pull request by RominaMarchetti**
1- Copy related to BiW updated on Controls screen. 

Screen Shot 2021-06-28 at 15 36 51

- Note: you will notice some extra changes in this prefabs because I resized all the keys images and the close button.

2-  `BuilderProjectsPanel` message style polished in this prefab as well.

Before
Screen Shot 2021-06-28 at 15 43 29

After
Screen Shot 2021-06-28 at 15 37 25

### CODE REVIEW

**Review by pbosio — CHANGES_REQUESTED** [review]
we should implement code to hide BiW related text in controls screen while feature is not active before merging this.
@Suduck @sandrade-dcl ?

**Comment by sandrade-dcl** [comment]
> we should implement code to hide BiW related text in controls screen while feature is not active before merging this.
> @Suduck @sandrade-dcl ?

It's a good point... yeah, as @pbosio says, I think we should hide the shortcut message when the feature flag is not active. @RominaMarchetti don't merge this PR yet, I'm going to add the corresponding change and I will let you know when it's ready.

**Review by sandrade-dcl — APPROVED** [review]
@pbosio I have added (and tested) the change related to the feature flag (https://github.com/decentraland/unity-renderer/pull/709/commits/c371c5d418815f6fa72a903b379e41d6ee089b79). Could you please take a look? Thanks!

@RominaMarchetti as soon as we have the Pato's approve, you can merge it! 👍

**Review by Suduck — APPROVED** [review]
Tested in zone and working!

**Review by pbosio — APPROVED** [review]

**Comment by RominaMarchetti** [comment]
Thank you all! @pbosio @sandrade-dcl @Suduck

**Pull request merged**
