### PR TITLE
feat: skybox satellite planar horizon

### PR DESCRIPTION
**Pull request by AjimenezDCL**
Counterpart PR: https://github.com/decentraland/unity-renderer/pull/2273

Three new features for procedural skybox:

Horizon Plane: New horizon plane is integrated with ground disc.
Satellite layer: Any prefab can be used as a satellite and it will render on the secondary camera.
Planar layer: This layer are specific for particle system prefabs. particle system should be of type circle or hemisphere only.

To test this PR: 
- Play around the world, the skybox configuration should be similar to the one in production
- There's a config reverted (68bb60128c23f1957d52cbd70bcbd7b43cbbed4d) with satellites and such, you can take it to test the skybox editor.
- Test the skybox editor `Window/Skybox Editor`. Best place to test it is in the `Test Scene` but bear in mind that playmode is not working properly in that scene, if you want to change the skybox in realtime (while playing) use the InitialScene.

### CODE REVIEW

**Comment by AjimenezDCL** [comment]
Dont forget Pravs requestes here: https://github.com/decentraland/unity-renderer/pull/2273

**Comment by AjimenezDCL** [comment]
https://play.decentraland.org/?renderer-branch=feat/skybox-satellite-planar-horizon

**Comment by AjimenezDCL** [comment]
I dont see degradation in performance. You can use the Performance meter tool for this:


```
Branch

PerformanceMeter - Data report step 2 - Processed values:
 * PERFORMANCE SCORE (0-100) -> 99.98
 * average FPS -> 134.1829
 * highest FPS -> 144
 * lowest FPS -> 85
 * 50 percentile (median) FPS -> 137
 * 95 percentile FPS -> 142
 * total hiccups (>0.05ms frames) -> 2 (0.05% of frames were hiccups)
 * total hiccups time (seconds) -> 0.1242065
 * total frames -> 4036
 * total frames time (seconds) -> 30.00036

PerformanceMeter - Data report step 2 - Processed values:
 * PERFORMANCE SCORE (0-100) -> 99.89
 * average FPS -> 137.1061
 * highest FPS -> 144
 * lowest FPS -> 28
 * 50 percentile (median) FPS -> 141
 * 95 percentile FPS -> 144
 * total hiccups (>0.05ms frames) -> 9 (0.22% of frames were hiccups)
 * total hiccups time (seconds) -> 0.8532982
 * total frames -> 4073
 * total frames time (seconds) -> 30.00056
 
 
 
 
 Master
 
 PerformanceMeter - Data report step 2 - Processed values:
 * PERFORMANCE SCORE (0-100) -> 99.95
 * average FPS -> 126.3477
 * highest FPS -> 136
 * lowest FPS -> 57
 * 50 percentile (median) FPS -> 129
 * 95 percentile FPS -> 135
 * total hiccups (>0.05ms frames) -> 4 (0.11% of frames were hiccups)
 * total hiccups time (seconds) -> 0.3999996
 * total frames -> 3794
 * total frames time (seconds) -> 30.00751
 
 PerformanceMeter - Data report step 2 - Processed values:
 * PERFORMANCE SCORE (0-100) -> 99.89
 * average FPS -> 135.6128
 * highest FPS -> 144
 * lowest FPS -> 21
 * 50 percentile (median) FPS -> 138
 * 95 percentile FPS -> 144
 * total hiccups (>0.05ms frames) -> 9 (0.22% of frames were hiccups)
 * total hiccups time (seconds) -> 0.8567982
 * total frames -> 4019
 * total frames time (seconds) -> 30.00311
```

**Review by Kinerius — APPROVED** [review]
The code looks good to me 👍

**Pull request merged**
